[build]
  command = "npm run build"
  publish = ".next/standalone"

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[functions]
  directory = "netlify/functions"